### ISSUE TITLE
Confusion about the camera extrinsics

### ISSUE THREAD

**Issue by Red-Fairy** [facebookresearch/co3d#77]
I am wondering whether the R and T in the frame_annotations define the cam2world matrix or the world2cam matrix. I thought it defines the cam2world matrix since all T have the third entry > 0, indicating that cameras are placed above the ground plane. However, the pytorch3D definition on cameras (https://pytorch3d.org/docs/cameras) says that the R, T defines the world2cam matrix.

I'm also confused about the location of objects in the world coordinate (z > 0 or z < 0?).  I thought the objects are placed above the ground plane (z>0), but the translation T indicates that they are below the ground plane (z<0), which seems strange to me.

Thanks in advance.

**Comment by shapovalov** [comment]
Hi Rundong.
Indeed, we use Pytorch3D format. If X is a an 1x3 point in the world coordinates, then you get to camera coordinates by (X@R + T). T is added after rotation, so you can’t judge about camera location by it. The camera centre in the world coords can be computed by −T@inv(R).

We don’t guarantee that the ground plane is aligned with the coordinate system (we did not run any plane detection).
Hope it helps. Please reopen the issue otherwise.

**Comment by Red-Fairy** [comment]
Thanks for your quick reply! 
However, I found −T@inv(R) has a negative third entry (i.e., z<0), indicating that the camera is below the ground plane. Is it a bug or just a normal phenomenon?
